// <auto-generated />
namespace EntityBuilding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Initial2Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial2Create));
        
        string IMigrationMetadata.Id
        {
            get { return "202112090842470_Initial2Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
