// <auto-generated />
namespace RecipesEShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Category_Ingredient_Relation_VE1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_Ingredient_Relation_VE1));
        
        string IMigrationMetadata.Id
        {
            get { return "202112010755145_Category_Ingredient_Relation_VE1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
